# Generated by Django 3.0.7 on 2020-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='product_color',
            field=models.ManyToManyField(through='order.CartWishlist', to='product.ProductColor'),
        ),
    ]
